//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GetAlertsSoap")]
    public interface GetAlertsSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumeWebService.ServiceReference1.HelloWorldResponse HelloWorld(ConsumeWebService.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ConsumeWebService.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name pass from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCounts", ReplyAction="*")]
        ConsumeWebService.ServiceReference1.GetCountsResponse GetCounts(ConsumeWebService.ServiceReference1.GetCountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCounts", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWebService.ServiceReference1.GetCountsResponse> GetCountsAsync(ConsumeWebService.ServiceReference1.GetCountsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebService.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumeWebService.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebService.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumeWebService.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCounts", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebService.ServiceReference1.GetCountsRequestBody Body;
        
        public GetCountsRequest() {
        }
        
        public GetCountsRequest(ConsumeWebService.ServiceReference1.GetCountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pass;
        
        public GetCountsRequestBody() {
        }
        
        public GetCountsRequestBody(string pass) {
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumeWebService.ServiceReference1.GetCountsResponseBody Body;
        
        public GetCountsResponse() {
        }
        
        public GetCountsResponse(ConsumeWebService.ServiceReference1.GetCountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountsResult;
        
        public GetCountsResponseBody() {
        }
        
        public GetCountsResponseBody(string GetCountsResult) {
            this.GetCountsResult = GetCountsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetAlertsSoapChannel : ConsumeWebService.ServiceReference1.GetAlertsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAlertsSoapClient : System.ServiceModel.ClientBase<ConsumeWebService.ServiceReference1.GetAlertsSoap>, ConsumeWebService.ServiceReference1.GetAlertsSoap {
        
        public GetAlertsSoapClient() {
        }
        
        public GetAlertsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetAlertsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAlertsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAlertsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebService.ServiceReference1.HelloWorldResponse ConsumeWebService.ServiceReference1.GetAlertsSoap.HelloWorld(ConsumeWebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumeWebService.ServiceReference1.HelloWorldRequest inValue = new ConsumeWebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumeWebService.ServiceReference1.HelloWorldRequestBody();
            ConsumeWebService.ServiceReference1.HelloWorldResponse retVal = ((ConsumeWebService.ServiceReference1.GetAlertsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebService.ServiceReference1.HelloWorldResponse> ConsumeWebService.ServiceReference1.GetAlertsSoap.HelloWorldAsync(ConsumeWebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ConsumeWebService.ServiceReference1.HelloWorldRequest inValue = new ConsumeWebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumeWebService.ServiceReference1.HelloWorldRequestBody();
            return ((ConsumeWebService.ServiceReference1.GetAlertsSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWebService.ServiceReference1.GetCountsResponse ConsumeWebService.ServiceReference1.GetAlertsSoap.GetCounts(ConsumeWebService.ServiceReference1.GetCountsRequest request) {
            return base.Channel.GetCounts(request);
        }
        
        public string GetCounts(string pass) {
            ConsumeWebService.ServiceReference1.GetCountsRequest inValue = new ConsumeWebService.ServiceReference1.GetCountsRequest();
            inValue.Body = new ConsumeWebService.ServiceReference1.GetCountsRequestBody();
            inValue.Body.pass = pass;
            ConsumeWebService.ServiceReference1.GetCountsResponse retVal = ((ConsumeWebService.ServiceReference1.GetAlertsSoap)(this)).GetCounts(inValue);
            return retVal.Body.GetCountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWebService.ServiceReference1.GetCountsResponse> ConsumeWebService.ServiceReference1.GetAlertsSoap.GetCountsAsync(ConsumeWebService.ServiceReference1.GetCountsRequest request) {
            return base.Channel.GetCountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWebService.ServiceReference1.GetCountsResponse> GetCountsAsync(string pass) {
            ConsumeWebService.ServiceReference1.GetCountsRequest inValue = new ConsumeWebService.ServiceReference1.GetCountsRequest();
            inValue.Body = new ConsumeWebService.ServiceReference1.GetCountsRequestBody();
            inValue.Body.pass = pass;
            return ((ConsumeWebService.ServiceReference1.GetAlertsSoap)(this)).GetCountsAsync(inValue);
        }
    }
}
